added submissions
impulsive-sudor/The-Dog-Blog pull request #5
Opened 2021-09-21 05:58 UTC by AnnVanBerg

I added  html, urls.py and views.py files. I was not sure if I was supposed to add to the existing or create new files.

2021-09-21 13:39 UTC, impulsive-sudor requested changes
I honestly recommend cloning the current main into another folder on your local computer and adding your adjusted code to that. Might be easier to sort out that way but I'm not the best with git, so might be wrong. I also need your models.py file.

2021-09-21 13:39 UTC, impulsive-sudor commented on dog_blog_project/dog_blog_app/templates/new.html
> +    </head>
Indentation is off here

2021-09-21 13:39 UTC, impulsive-sudor commented on dog_blog_project/dog_blog_app/templates/new.html
> +<body id="bg" style="background-image: url('{% static "media/3 pups.png" %}');">
This picture will not load since it's not being posted to github. Might be better to use a picture off google or bing for demonstration.

2021-09-21 13:39 UTC, impulsive-sudor commented on dog_blog_project/dog_blog_app/templates/new.html
> +                                    </div>
I'm not sure what's going on with this Div tag

2021-09-21 13:39 UTC, impulsive-sudor commented on dog_blog_project/dog_blog_app/templates/new.html
> +                                    </div>
I'm not sure what's going on with this Div tag

2021-09-21 13:39 UTC, impulsive-sudor commented on dog_blog_project/dog_blog_app/templates/new.html
> +                    <form>
The form is as the same level as the divs.

2021-09-21 13:39 UTC, impulsive-sudor commented on dog_blog_project/dog_blog_app/templates/new.html
> +                        </form>
Form close is indented wrong and confused because the next few lines are also part of the form?

2021-09-21 13:39 UTC, impulsive-sudor commented on dog_blog_project/dog_blog_app/templates/new.html
> +                    <center>
This code should link into the upload form I created

2021-09-21 13:39 UTC, impulsive-sudor commented on dog_blog_project/dog_blog_app/urls copy.py
> +path('new', views.new),
This is indented wrong

2021-09-21 13:39 UTC, impulsive-sudor commented on dog_blog_project/dog_blog_app/urls copy.py
> +from django.urls import path
You should be using urls.py not urls copy.py

2021-09-21 13:39 UTC, impulsive-sudor commented on dog_blog_project/dog_blog_app/views copy.py
> +
We should be using views.py not views copy.py

2021-09-21 13:39 UTC, impulsive-sudor commented on dog_blog_project/dog_blog_app/views copy.py
> +def new(request):
User needs to be logged in to submit a post, we should keep the user session validation.

2021-09-21 13:39 UTC, impulsive-sudor commented on dog_blog_project/dog_blog_app/views copy.py
> +    Dog.objects.create(
Where is the model for this?

2021-09-21 13:39 UTC, impulsive-sudor commented on dog_blog_project/dog_blog_app/views copy.py
> +    Dog.objects.create(
Also, the object creation is outside the if else statement.

2021-09-21 13:39 UTC, impulsive-sudor commented on dog_blog_project/dog_blog_app/views copy.py
> +    if len(errors) > 0:
So we are looking for errors but where is the update_validator? Also, what is Apt?

2021-09-22 06:04 UTC, amyhuang0419 commented on dog_blog_project/dog_blog_app/templates/new.html
> +<body id="bg" style="background-image: url('{% static "media/3 pups.png" %}');">
Use the online image to instead of the image which you load from your local.

2021-09-22 06:31 UTC, amyhuang0419 commented on dog_blog_project/dog_blog_app/views copy.py
> +def new(request):
we need to add the user_id or use request.session['user_id'] here to make sure the post which user upload belong to his own.

2021-09-22 13:17 UTC, impulsive-sudor commented
> I added html, urls.py and views.py files. I was not sure if I was supposed to add to the existing or create new files.


Yes, you should be editing the current files, that's the benefit of using git. There was a handful of training videos on it, I recommend checking them out. 

We need your code by tonight, otherwise I need to make these changes for you.

2021-09-23 09:56 UTC, impulsive-sudor commented
Closing pull request, submission page completed by Nick.

2021-09-23 09:56 UTC, closed without merging